### PR TITLE
Fix: apply musical scales for pwm buzzer test

### PR DESCRIPTION
**Pull request by stanley31huang**
apply musical scales for pwm buzzer test

### CODE REVIEW

**Review by LiaoU3 — APPROVED** [review]
LGTM

**Comment by patliuu** [comment]
Hi @stanley31huang ,
I would suggest adding a brief explanation to this PR and maybe also providing a sideload result.

**Comment by stanley31huang** [comment]
Please have the test results as following, as we only applied the patch for pwm buzzer test
```
iotuc@ubuntu:~$ sudo ./buzzer_test.sh -n pw1 -c 0 -p 0 -e 1 -t pwm
## pwm is activated
## Start pwm Buzzer pw1 test
## Set pwm 0 to 1
Configure pwm chip0 pwm0
Setting up duty cycle to 0.125 sec
Setting up period to 3816793 nano seconds
Setting up period to 3610108 nano seconds
Setting up period to 3401360 nano seconds
Setting up period to 3215434 nano seconds
Setting up period to 3030303 nano seconds
Setting up period to 2865329 nano seconds
Setting up period to 2702702 nano seconds
Setting up period to 2551020 nano seconds
Setting up period to 2409638 nano seconds
Do you hear the sound from buzzer pw1? (y/n)
y
## Set pwm 0 to 0
Is the buzzer pw1 stop? (y/n)
y
Buzzer pw1 test: PASSED
```

**Review by patliuu — APPROVED** [review]
LGTM

**Pull request merged**
