### PR TITLE
Fix: wrong name of after-suspend-eeprom-automated

### PR DESCRIPTION
**Pull request by LiaoU3**
# Description
The name of test plan `after-suspend-eeprom-automated` is wrong, it should be `after-suspend-ce-oem-eeprom-automated`

### CODE REVIEW

**Review by stanley31huang — APPROVED** [review]
LGTM

**Review by baconYao — APPROVED** [review]
LGTM

**Review by rickwu666666 — CHANGES_REQUESTED** [review]
This feature has been migrated back to PPC already.
https://github.com/canonical/checkbox/pull/350
Therefore, you may remove it instead of patching this job.
Please make sure you include the test plan from PPC to ce-oem test plan.
And if you are going to do so, please take this [jira card](https://warthogs.atlassian.net/browse/CQT-2013) over. Thanks a lots.

**Review by rickwu666666 — APPROVED** [review]
After discussing offline. This patch could go first. We can remove it later on.

**Pull request merged**
