### PR TITLE
Add optee test

### PR DESCRIPTION
**Pull request by rickwu666666**
We migrate OP-TEE release test from another project.
This is sideloaded result without manifest.
https://pastebin.canonical.com/p/NCrxC5Yk88/

### CODE REVIEW

**Review by patliuu — APPROVED** [review]
LGTM

**Review by stanley31huang — CHANGES_REQUESTED** [review]
per our discussion, we might need perform optee test with the xtest utility in gadget snap.

**Comment by rickwu666666** [comment]
> per our discussion, we might need perform optee test with the xtest utility in gadget snap.

Updated! Please help to review it again.
sideload result:
https://certification.canonical.com/hardware/202304-31535/submission/326525/

The result if not found xtest in gadget snap.
https://pastebin.canonical.com/p/S7q2NKwfzt/

**Comment by stanley31huang** [comment]
LGTM

**Review by stanley31huang — APPROVED** [review]
Thanks for the changes, LGTM.

**Pull request merged**
