### PR TITLE
Fix script for pep8 check

### PR DESCRIPTION
**Pull request by rickwu666666**
Fix: python script to fit flake8

Remove: test job/script that is not in use.

Since we have a new script for cpu freq governors.

And also cpu_offline test has been updated in the base provider.

### CODE REVIEW

**Comment by hanhsuan** [comment]
Will you fix shellcheck warnings in other PR? [I check your code, there are some warning from shellcheck](https://github.com/hanhsuan/checkbox-provider-ce-oem/actions/runs/5459658211/jobs/9935877925)

**Comment by rickwu666666** [comment]
> Will you fix shellcheck warnings in other PR? [I check your code, there are some warning from shellcheck](https://github.com/hanhsuan/checkbox-provider-ce-oem/actions/runs/5459658211/jobs/9935877925)

yes, let us do it in other PR to make it simpler.

**Review by hanhsuan — APPROVED** [review]
LGTM

**Review by patliuu — APPROVED** [review]
LGTM +1

**Pull request merged**
